SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B1.CATEGORY, SUM(B1.PRICE * B2.SALES) AS TOTAL_SALES
FROM BOOK B1
INNER JOIN BOOK_SALES B2 ON B2.BOOK_ID = B1.BOOK_ID
INNER JOIN AUTHOR A ON A.AUTHOR_ID = B1.AUTHOR_ID
WHERE TO_CHAR(B2.SALES_DATE,'YYYY-MM') = '2022-01'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B1.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B1.CATEGORY DESC;