SELECT F.ORDER_ID, F.PRODUCT_ID, TO_CHAR(F.OUT_DATE, 'YYYY-MM-DD') AS OUT_DATE,
    CASE WHEN F.OUT_DATE <= TO_DATE('2022-05-01', 'YYYY-MM-DD') THEN '출고완료'
         WHEN F.OUT_dATE > TO_DATE('2022-05-01', 'YYYY-MM-DD') THEN '출고대기'
         ELSE '출고미정'
    END AS 출고여부
FROM FOOD_ORDER F
ORDER BY F.ORDER_ID ASC;
