SELECT U1.USER_ID, U1.NICKNAME, U1.CITY || ' ' || U1.STREET_ADDRESS1 || ' ' || U1.STREET_ADDRESS2 AS 전체주소,
SUBSTR(U1.TLNO, 1, 3) || '-' || SUBSTR(U1.TLNO, 4, 4) || '-' || SUBSTR(U1.TLNO, 8, 4)  AS 전화번호
FROM USED_GOODS_USER U1
INNER JOIN USED_GOODS_BOARD U2 ON U1.USER_ID = U2.WRITER_ID
GROUP BY U1.USER_ID, U1.NICKNAME, U1.CITY, U1.STREET_ADDRESS1, U1.STREET_ADDRESS2, U1.TLNO
HAVING COUNT(USER_ID) >= 3
ORDER BY U1.USER_ID DESC;