SELECT A1.ANIMAL_ID, A1.ANIMAL_TYPE, A1.NAME
FROM ANIMAL_OUTS A1
INNER JOIN ANIMAL_INS A2 ON A1.ANIMAL_ID = A2.ANIMAL_ID
WHERE A2.SEX_UPON_INTAKE LIKE 'Intact%'
AND (A1.SEX_UPON_OUTCOME LIKE 'Spayed%' OR A1.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY A1.ANIMAL_ID ASC;
