SELECT R2.REST_ID, R2.REST_NAME, R2.FOOD_TYPE, R2.FAVORITES, R2.ADDRESS, ROUND(AVG(R1.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW R1
INNER JOIN REST_INFO R2 ON R1.REST_ID = R2.REST_ID
WHERE R2.ADDRESS LIKE '서울%'
GROUP BY R2.REST_ID, R2.REST_NAME, R2.FOOD_TYPE, R2.FAVORITES, R2.ADDRESS
ORDER BY SCORE DESC, R2.FAVORITES DESC;