SELECT C.HISTORY_ID, C.CAR_ID, TO_CHAR(C.START_DATE, 'YYYY-MM-DD') AS START_DATE, TO_CHAR(C.END_DATE, 'YYYY-MM-DD') AS END_DATE,
    CASE WHEN (C.END_DATE - C.START_DATE) >= 29 THEN '장기 대여'
         WHEN (C.END_DATE - C.START_DATE) < 30 THEN '단기 대여'
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
WHERE EXTRACT(YEAR FROM C.START_DATE) = 2022 AND EXTRACT(MONTH FROM C.START_DATE) = 9
ORDER BY C.HISTORY_ID DESC;