WITH GET_AVG AS (
    SELECT CAR_ID, ROUND(AVG(C.END_DATE - C.START_DATE + 1), 1) AS AVERAGE_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    GROUP BY CAR_ID
    HAVING AVG(C.END_DATE - C.START_DATE + 1) >= 7
)

SELECT CAR_ID, AVERAGE_DURATION
FROM GET_AVG
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;