SELECT F1.PRODUCT_ID, F2.PRODUCT_NAME, SUM(F1.AMOUNT * F2.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER F1
INNER JOIN FOOD_PRODUCT F2 ON F1.PRODUCT_ID = F2.PRODUCT_ID
WHERE TO_CHAR(F1.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY F1.PRODUCT_ID, F2.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, F1.PRODUCT_ID ASC;