SELECT U1.USER_ID, U1.NICKNAME, SUM(U2.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER U1
INNER JOIN USED_GOODS_BOARD U2 ON U1.USER_ID = U2.WRITER_ID
WHERE U2.STATUS = 'DONE'
GROUP BY U1.USER_ID, U1.NICKNAME
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;