SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
WHERE (MONTH(C.START_DATE) BETWEEN 8 AND 10) AND C.CAR_ID IN (
    SELECT TEMP.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY TEMP
    WHERE MONTH(TEMP.START_DATE) BETWEEN 8 AND 10
    GROUP BY TEMP.CAR_ID
    HAVING COUNT(*) >= 5
)
GROUP BY MONTH, C.CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH ASC, C.CAR_ID DESC;


