SELECT DISTINCT C1.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C1
INNER JOIN CAR_RENTAL_COMPANY_CAR C2 ON C1.CAR_ID = C2.CAR_ID
WHERE C2.CAR_TYPE = '세단' AND EXTRACT(MONTH FROM C1.START_DATE) = 10
ORDER BY C1.CAR_ID DESC;