SELECT U2.TITLE, U2.BOARD_ID, U1.REPLY_ID, U1.WRITER_ID, U1.CONTENTS, TO_CHAR(U1.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE 
FROM USED_GOODS_REPLY U1
INNER JOIN USED_GOODS_BOARD U2 ON U1.BOARD_ID = U2.BOARD_ID
WHERE TO_CHAR(U2.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY CREATED_DATE ASC, U2.TITLE ASC;