SELECT H1.DEPT_ID, H1.DEPT_NAME_EN, ROUND(AVG(H2.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT AS H1
INNER JOIN HR_EMPLOYEES AS H2 ON H1.DEPT_ID = H2.DEPT_ID
GROUP BY H1.DEPT_ID, H1.DEPT_NAME_EN
ORDER BY AVG(H2.SAL) DESC;