SELECT '/home/grep/src/' || U2.BOARD_ID || '/' || U1.FILE_ID || U1.FILE_NAME || U1.FILE_EXT AS FILE_PATH
FROM USED_GOODS_FILE U1
INNER JOIN USED_GOODS_BOARD U2 ON U1.BOARD_ID = U2.BOARD_ID
WHERE U2.VIEWS IN (
    SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD
)
ORDER BY U1.FILE_ID DESC;
