SELECT F1.CATEGORY, F1.PRICE, F1.PRODUCT_NAME
FROM FOOD_PRODUCT F1
WHERE (F1.CATEGORY, F1.PRICE) IN (
    SELECT F2.CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT F2
    GROUP BY F2.CATEGORY
    HAVING F2.CATEGORY IN ('과자', '국', '김치', '식용유')
)
ORDER BY F1.PRICE DESC;

